apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ if .Values.service.targetPort | default .Values.service.port | quote }}
  selector:
    app: techtrends
    tag: latest
  type: {{ .Values.service.type }} 
